# AUTOGENERATED! DO NOT EDIT! File to edit: FastAI_Lesson2_APPDeploy.ipynb.

# %% auto 0
__all__ = ['learner_inf', 'categories', 'image', 'labels', 'examples', 'intf', 'classify_img']

# %% FastAI_Lesson2_APPDeploy.ipynb 3
import os
os.system('pip install --upgrade pip')
os.system('pip install -r requirements.txt')

# %% FastAI_Lesson2_APPDeploy.ipynb 4
from fastai.vision.all import *
import gradio as gr

# %% FastAI_Lesson2_APPDeploy.ipynb 7
learner_inf = load_learner('bears_model.pkl')

# %% FastAI_Lesson2_APPDeploy.ipynb 8
categories = ('grizzly', 'black', 'teddy')

def classify_img(img):
  pred, idx, prob = learner_inf.predict(img)
  return dict(zip(categories, map(float, prob)))

# %% FastAI_Lesson2_APPDeploy.ipynb 10
image = gr.Image(shape=(192, 192))
labels = gr.Label()
examples = [
    "/content/gdrive/MyDrive/ColabNotebooks/FastAI/Class2/Datasets/grizzly.jpg",
    "/content/gdrive/MyDrive/ColabNotebooks/FastAI/Class2/Datasets/black.jpg",
    "/content/gdrive/MyDrive/ColabNotebooks/FastAI/Class2/Datasets/teddy.jpg"
]

intf = gr.Interface(fn=classify_img, inputs=image, outputs=labels, examples=examples)
intf.launch(inline=False)
